Add controllers
melkoto/java-shareit pull request #1
Opened 2023-06-13 21:17 UTC by melkoto

2023-06-13 21:20 UTC, melkoto commented
Часть кода в сыром виде. Делал только по требованиям ТЗ и тестов постмана. Сроки сильно поджимают, поэтому надеюсь, что сможешь проверить оперативно. Если можно, оставьте коммент где поправить, пжл. Я обязательно с следующим ПР поправлю. Работа, учеба и ЯП очень сложно пока с временем. Хочу сразу же начать 14 спринт

Спасибо!

2023-06-14 19:55 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-06-14 19:55 UTC, FanaticFiz commented on README.md
> +
`pom` файл не менялся.
Напишу коммент в произвольном месте...

1. Хорошей практикой будет указать кодировку
`<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>`

2. Я советую всем соблюдать некий порядок при объявлении зависимостей.
Сначала "главный" `spring` все его зависимости и всё о нём.
Потом по степени "тяжеловестности" остальные зависимости. Ну и у меня в проекте, например, последними идёт еще одна секция наши собственные библиотеки/модули/контракты.

2023-06-14 19:55 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemResponseDto addItem(@Valid @RequestBody CreateItemRequestDto item, @RequestHeader(value = "X-Sharer-User-Id") long userId) {
Максимальная длинна строки 120 символов. Настраиваем форматтер и не забываем применять.

2023-06-14 19:55 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (userStorage.getUser(userId) == null) {
`Optional` - метод в хранилище должен возвращать `Optional<User>` - это позволит писать более удобный код в функциональном стиле.

2023-06-14 19:55 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (userStorage.getUser(userId) == null) {
`Optional` - метод в хранилище должен возвращать `Optional<User>` - это позволит писать более удобный код в функциональном стиле.

2023-06-14 19:55 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        User user = userStorage.getUser(userId);
`getUser` - ты уже делал это несколькими строками ранее.
Но я думаю Optional это подлечит ))

2023-06-14 19:55 UTC, FanaticFiz commented on src/main/resources/application.properties
>  spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect
Что там на счет свойств в YAML формате?

2023-06-14 19:55 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/storage/UserStorage.java
> +    Map<String, User> getEmails();
Не нужно отдавать наружу это...
Посмотри как ты работаешь с этим - ищешь вхождение email - так сделай в хранилище метод: `isExistByEmail()` or `isNotExistByEmail()` как тебе удобно...

2023-06-14 19:55 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/storage/UserStorage.java
> +    User getUser(long id);
Давай разграничивать хранилища и сервисы с помощью глаголов.
В хранилищах - `find`
В сервисах - `get`

2023-06-14 19:55 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +    public List<Item> getItems(long userId) {
Мне не нравится совпадение имени с уже существующим методом. 
Я не говорю что это прям плохо, но кажется можно же быть более выразительными: `getUserItems()` or `getOwnerItems()`

2023-06-17 06:18 UTC, FanaticFiz approved these changes

2023-06-17 06:18 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        User user = userStorage.findUser(userId).orElseThrow(() -> new NotFoundException("Пользователь с id = " + userId + " не найден"));
Ну длинная же строка, не более 120 символов, должна быть.

А нужно делать вот что - всегда переноси код в цепочках, каждую новую операцию с новой строки.

А еще можно перестроить фразу, чтобы строка получалась короче, без вставки в середину.

```
        User user = userStorage.findUser(userId)
                               .orElseThrow(() -> new NotFoundException("Не найден пользователь с id = " + userId));
```

2023-06-17 06:18 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (itemStorage.findItem(itemId) == null) {
1. Почему `findItem` без `Optional` ?
2. Почему ты делаешь `userStorage.findUser` с последующей проверкой и не используешь `orElseThrow`, как делал вот в соседнем методе?

Нужно писать код единообразно. Применяя одинаковые подходы по всему коду.

2023-06-17 06:18 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +        if (userStorage.isExistByEmail(userEntity.getEmail())
Кажется ты тут переборщил и один лишний раз проверяешь isExistByEmail

2023-06-17 06:18 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +        User user = userStorage.findUser(id)
Переписать в одну строку - сразу `return ........`
Ты уже так делал!

2023-06-17 18:11 UTC, merged