Add item requests
melkoto/java-shareit pull request #3
Opened 2023-06-24 21:54 UTC by melkoto

2023-06-27 20:46 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-06-27 20:46 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +    public ItemRequestServiceImpl(ItemRequestRepository itemRequestRepository, UserRepository userRepository, ItemRepository itemRepository) {
Too long string!

2023-06-27 20:46 UTC, FanaticFiz commented on src/test/java/ru/practicum/shareit/item/mapper/ItemMapperTest.java
> +        LongItemResponseDto result = mapItemToItemResponseDto(item, lastBooking, nextBooking, comments);
Так `comments` и остались `null` - это ошибка и можно было бы их и не заводить или что то пропущено?

2023-06-27 20:52 UTC, melkoto commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        if (from < 0 || size <= 0) {
Спасибо! Не знал ))

2023-06-28 07:15 UTC, FanaticFiz approved these changes

2023-06-28 08:02 UTC, merged